/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentProfileRouteImport } from './routes/agent-profile'
import { Route as AgentNetworkRouteImport } from './routes/agent-network'
import { Route as AgentLRouteImport } from './routes/agent-l'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/agent-profile',
  path: '/agent-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentNetworkRoute = AgentNetworkRouteImport.update({
  id: '/agent-network',
  path: '/agent-network',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLRoute = AgentLRouteImport.update({
  id: '/agent-l',
  path: '/agent-l',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-l': typeof AgentLRoute
  '/agent-network': typeof AgentNetworkRoute
  '/agent-profile': typeof AgentProfileRoute
  '/auth': typeof AuthRoute
  '/confirmation': typeof ConfirmationRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-l': typeof AgentLRoute
  '/agent-network': typeof AgentNetworkRoute
  '/agent-profile': typeof AgentProfileRoute
  '/auth': typeof AuthRoute
  '/confirmation': typeof ConfirmationRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-l': typeof AgentLRoute
  '/agent-network': typeof AgentNetworkRoute
  '/agent-profile': typeof AgentProfileRoute
  '/auth': typeof AuthRoute
  '/confirmation': typeof ConfirmationRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-l'
    | '/agent-network'
    | '/agent-profile'
    | '/auth'
    | '/confirmation'
    | '/onboarding'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-l'
    | '/agent-network'
    | '/agent-profile'
    | '/auth'
    | '/confirmation'
    | '/onboarding'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/agent-l'
    | '/agent-network'
    | '/agent-profile'
    | '/auth'
    | '/confirmation'
    | '/onboarding'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentLRoute: typeof AgentLRoute
  AgentNetworkRoute: typeof AgentNetworkRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AuthRoute: typeof AuthRoute
  ConfirmationRoute: typeof ConfirmationRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-profile': {
      id: '/agent-profile'
      path: '/agent-profile'
      fullPath: '/agent-profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-network': {
      id: '/agent-network'
      path: '/agent-network'
      fullPath: '/agent-network'
      preLoaderRoute: typeof AgentNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-l': {
      id: '/agent-l'
      path: '/agent-l'
      fullPath: '/agent-l'
      preLoaderRoute: typeof AgentLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentLRoute: AgentLRoute,
  AgentNetworkRoute: AgentNetworkRoute,
  AgentProfileRoute: AgentProfileRoute,
  AuthRoute: AuthRoute,
  ConfirmationRoute: ConfirmationRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
