// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqqrndyxrztxykecbrzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcXJuZHl4cnp0eHlrZWNicnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMyMTAwMzksImV4cCI6MjA5ODc4NjAzOX0.JaCddkKoC4xy_Zq0uCPdKfgZGFjJ1BSS4dkDwsgcyPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});